extract_job_requirements:
  description: >
    Your primary objective is to extract and categorize all key skills, experiences, and qualifications from the job advertisement.
    1. Use DirectoryReadTool to list all files and confirm the presence of **job_advertise.md**.
    2. Use FileReadTool and/or MDXSearchTool to read the full contents of **job_advertise.md**.
    3. Make a checklist of files read and verify against DirectoryReadTool output.
    4. Identify each required skill, qualification, and experience.
    5. Categorize requirements into:
       - Technical skills
       - Soft skills
       - Education & certifications
       - Professional experience
    If any files cannot be read, explicitly state the missing files.
  expected_output: >
    A structured YAML list detailing:
    - technical_skills: [...]
    - soft_skills: [...]
    - education_and_certifications: [...]
    - professional_experience: [...]
    Additionally, include a “files_read” section listing all files accessed for verification.
  agent: researcher
  human_input: true

compile_candidate_profile:
  description: >
    Compile a comprehensive personal and professional profile using the provided resume versions and guidance notes.
    1. Use DirectoryReadTool to list all **cv_*.md** and **notes.md** files.
    2. Read each **cv_*.md** and **notes.md** using FileReadTool and/or MDXSearchTool.
    3. Verify all expected files are read; list any missing ones.
    4. Use all the information in all the provided CVs to craft a new CV with the following sections:
       - personal_information
       - core_skills
       - project_experiences
       - contributions_and_achievements
       - interests_and_values
       - communication_style
    5. Maintain fidelity to source documents; do not hallucinate.
  expected_output: >
    A detailed profile document string structured as a YAML object with the sections above,
    and a “files_read” list for auditability.
    Additionally, include a “files_read” section listing all files accessed for verification.
  agent: profiler
  human_input: true

tailor_resume:
  description: >
    Using the outputs from **extract_job_requirements** and **compile_candidate_profile**, 
    tailor the candidate’s new resume:
    1. Load previous tasks outputs (requirements and profile).
    2. Use all the info in the provided curriculum from the candidate
    3. Create and craft each section of the new resume:
       - summary
       - work_experience
       - skills
       - education
    4. Emphasize alignment between candidate’s strengths and job requirements.
    5. Use FileReadTool and FileWriterTool with full paths to read/update/write **new_resume.md**.
    6. Validate that no information is invented beyond source documents.
  expected_output: >
    An updated **new_resume.md** file saved via FileWriterTool, containing:
    - revised summary
    - reorganized work_experience entries
    - highlighted skills
    - tailored education section
    Plus a YAML “changes_log” summarizing edits.
    The resume **MUST** include all the information found in the provided CVs relevant to the job application.
    Also, not relevant information shall not be cut our completely but it is importnat to include finding a way 
    so that they are also included.
    Tailoring a resume for a specific job application does not mean not mentioning candidate's job experiences or 
    knowledge not relevant to the advertise.
    Tailoring means only making the matching knowledge and skills be more relevant
  agent: resume_strategist
  output_file: "new_resume.md"
  human_input: true

