extract_job_requirements:
  description: >
    Your primary objective is to extract and categorize all key skills, experiences, and qualifications 
    from the job advertisement.
    1. Use FileReadTool and/or MDXSearchTool to read the full contents of the job descrition {job_desc_path}
    2. Use FileReadTool and/or MDXSearchTool to read the full contents of the resume {resume_path}
    3. Extract key terms and phrases for ATS comparison by using the KeywordsAnalyzerTool:
       - use the table that the KeywordsAnalyzerTool will output
       - Identify keywords not present in the resume
    4. Search web via SerperDevTool and ScrapeWebsiteTool and use the LLM with the sole purpose to add all 
       the missing keywords from the job description to the resume
       Create a nice story how to integrate those words in the resume
    If any files cannot be read, explicitly state the missing files.
  expected_output: >
    A structured list detailing:
    - technical_skills: [...]
    - soft_skills: [...]
    - education_and_certifications: [...]
    - professional_experience: [...]
    Additionally, when you are done, include a “files_read” section listing all files accessed for verification.
  agent: researcher

tailor_resume:
  description: >
    Compile a comprehensive personal and professional profile using the provided resume.
    Use all the information provided by the previous task.
    1. Use FileReadTool and/or MDXSearchTool to read the full contents of the job descrition {job_desc_path}
    2. Use FileReadTool and/or MDXSearchTool to read the full contents of the resume {resume_path}
    3. Verify all expected files are read; list any missing ones.
    4. Craft a new resume based on the old one and the suggestions from the previous task 
    5. Maintain fidelity to source documents; do not hallucinate.
    6. Use the KeywordsAnalyzerTool against the new resume you created and the job advertise, if the words matching or the 
       cosine similiarity is less than 85%, craft a new resume taking in cosnideration the table of missing keywords from the
       job advertise to the resume you create.
    7. Repeat the process as many times you need until the KeywordsAnalyzerTool used to compare the new resume you created and 
       the job advertise words matching and the cosine similiarity equal or greater than 85%.
       If it is not repeat all the points above again.
  expected_output: >
    A detailed resume in MD format with at least below and a KeywordsAnalyzerTool keyword matching and cosine similarity not less than 85%
    - revised summary
    - reorganized work_experience entries
    - highlighted skills
    - tailored education section
    - Objective Statement summarizing key skills and experience relevant to the target role
    - Specific project details and measurable accomplishments
    - **EXTREMLY IMPORTANT** the generated resume **MUST** be compared with the with KeywordsAnalyzerTool and the job 
      description and if it is less than 85% do it again and again untill you reach a scoring greather than 85%
    - **MANDATORY** Output the newly generated resume and the result of the newly gemnerated resume compared with 
      KeywordsAnalyzerTool and the job description and wait for the human input.
  agent: resume_strategist
  human_input: true
  markdown: true
  output_file: new_resume.md

